### ISSUE TITLE
Inclusion in Infiltrator

### ISSUE THREAD

**Issue by pfitzseb** [antoine-levitt/Exfiltrator.jl#6]
Hey, just as a heads up: While getting Infiltrator ready for a 1.0 release I also added an `@exfiltrate` macro (ref https://github.com/JuliaDebug/Infiltrator.jl/pull/35). 
It works slightly different than Exfiltrators, but the idea is the same.

**Comment by antoine-levitt** [comment]
Oh great! I'd love to deprecate this and just point to infiltrator. The design in Infiltrator is much cleaner than the one here. However it's also a bit less easy to use
- It doesn't support `@exfiltrate x y z` to only exfiltrate a subset of variables, although I guess if it's in a separate namespace it's less useful and you can just exfiltrate everything.
- I kind of liked `@exfiltrate_push!` eg to plot something alongside iterations of an algorithms. But I guess one can just do `push!(get_scratch_pad().var, something)`.
- Having to do get_scratch_pad() to access the variables is a bit annoying, esp. because you lose autocompletion, although I do get the point that it's better than just pushing it into the global namespace. Maybe a SCRATCH global variable would be easier to access? If you're concerned wanting custom logic for accessing it, maybe getproperty overloading would be the way to go?

**Comment by antoine-levitt** [comment]
Concerns addressed, I added a mention to the README redirecting users to use Infiltrator instead of Exfiltrator. Thanks a lot!
